### ISSUE TITLE
How to add m own quantized terrain mesh in TerriaMap ?

### ISSUE THREAD

**Issue by spaciandd** [TerriaJS/TerriaMap#380]
I have customized my config.json like following:
**"useCesiumIonTerrain": false,
 "cesiumTerrainUrl": "https://api.maptiler.com/tiles/terrain-quantized-mesh/?key=<my-key>"**

and I have tested its OK, but what i want is to show this in Map View Window, so that user can switch to this on desire. (See attach image)

![Screenshot_2](https://user-images.githubusercontent.com/33995618/64609670-de7a3300-d3e6-11e9-93a0-7cb9e4e78e1c.png)

**Comment by steve9164** [comment]
HI @spaciandd. Normally we use the above buttons "3D Terrain" and "3D Smooth" to switch the use of streamed terrain on and off. I think it'd be tricky to work a terrain provider into the base maps section. 

You could change the settings panel if you're familiar with React either by forking terriajs (and pointing to your fork on github in package.json) or by copying some jsx files from terriajs, slightly modifying them in your TerriaMap and using them instead of the terriajs ones (start at StandardUserInterface.jsx from terriajs)

**Comment by steve9164** [comment]
I'm going to close this, but if you have more to add please let us know. Also we have a live community chat at https://gitter.im/TerriaJS/terriajs as well as a group at https://groups.google.com/forum/#!forum/terriajs
