### ISSUE TITLE
Any examples of visualizing LiDAR data in National Map?

### ISSUE THREAD

**Issue by rsignell-usgs** [TerriaJS/TerriaMap#7]
There is a USGS LiDAR Science Workshop, sponsored by the 3D Elevation Program (3DEP) scheduled for August 2-4 at CSU in Fort Collins, CO, USA, and I was wondering what the capabilities of TerriaJS/Cesium were with respect to LiDAR. 

I tried to find examples of visualizing LiDAR data in the National Map, but all I could find were tile indexes like this:
![2016-03-09_9-20-14](https://cloud.githubusercontent.com/assets/1872600/13638140/ec23621a-e5d8-11e5-9b55-9808f9a8b7dc.jpg)

I was hoping for something like 3D terrain draped with color-shaded relief...

Are there any examples?

**Comment by kring** [comment]
@rsignell-usgs I don't know of any concrete examples offhand, but I can say this...  If the LiDAR data has been processed to produce a heightmap, it's fairly easy to get that into TerriaJS/Cesium as a terrain provider.  The easiest way is to use [STK Terrain Server](http://www.agi.com/products/stk/terrain-server/), which makes it extremely easy: just drag/drop the heightmap file into the app and it quickly creates tiles ready to be served to Cesium.  STK Terrain Server created and hosts the public, worldwide terrain you see by default in Cesium.

An open-source option, created by members of the community rather than AGI, is [Cesium Terrain Builder](https://github.com/geo-data/cesium-terrain-builder).

In Cesium, the terrain geometry is separate from the coloring of the terrain.  To get a shaded relief, you can create an image in, say, GeoTIFF format using GDAL or another tool, and then serve it to Cesium using any of its supported imagery providers (e.g. load it into Geoserver and serve it to Cesium via WMS, or use ArcGIS Server, or cut it into tiles with gdal2tiles.py, serve the tiles with a normal web server, and access them with Cesium's `TileMapServerImageryProvider`.)

If the LiDAR data is more like a point cloud, it may be possible to visualize it using [Cesium 3D Tiles](http://cesiumjs.org/2015/08/10/Introducing-3D-Tiles/).  That's a work in progress.
